"""empty message

Revision ID: 99ba18168f02
Revises: None
Create Date: 2017-10-18 22:59:22.317301

"""

# revision identifiers, used by Alembic.
revision = '99ba18168f02'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_column('status')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('poll',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_modified', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
